FROM python:3.12.7

WORKDIR /remind_service

RUN pip install --upgrade pip "poetry==1.8.4"
RUN poetry config virtualenvs.create false --local

COPY remind/pyproject.toml ./
COPY remind/poetry.lock ./

RUN poetry install

COPY remind ./remind
COPY wait-for-it.sh ./

#CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]