services:
  backend:
    build:
      dockerfile: Dockerfile-Backend
    command:
      - "uvicorn"
      - "main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
  db:
    image: postgres:16.4
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

volumes:
  postgres_data: