FROM python:3.12.7

WORKDIR /app

RUN pip install --upgrade pip "poetry==1.8.4"
RUN poetry config virtualenvs.create false --local

COPY backend/pyproject.toml ./
COPY backend/poetry.lock ./

RUN poetry install

COPY backend ./backend
COPY wait-for-it.sh ./

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]