FROM python:3.12.7

WORKDIR /remind_service

RUN apt-get update && apt-get install -y supervisor

RUN pip install --upgrade pip "poetry==1.8.4"
RUN poetry config virtualenvs.create false --local

COPY remind/pyproject.toml ./
COPY remind/poetry.lock ./

RUN poetry install

COPY supervisord_celery.conf /etc/supervisor/conf.d/supervisord.conf

COPY remind ./remind
COPY wait-for-it.sh ./

ENV CELERY_BROKER_URL=redis://redis:6379/0
ENV CELERY_RESULT_BACKEND=redis://redis:6379/0

CMD ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]