services:
  backend:
    build:
      dockerfile: Dockerfile-Backend
    command:
      - "./wait-for-it.sh"
      - "db_backend:5432"
      -  "--"
      - "uvicorn"
      - "backend.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db_backend
    restart: always

  db_backend:
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER_BACKEND}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_BACKEND}
      POSTGRES_DB: ${POSTGRES_DB_BACKEND}
    ports:
      - "5432:5432"
    volumes:
      - backend_data:/var/lib/postgresql/data/
    restart: always

  frontend:
    build:
      dockerfile: Dockerfile-Frontend
    command:
      - "./wait-for-it.sh"
      - "db_frontend:5432"
      - "--"
      - "python"
      - "-m"
      - "frontend.telegram_bot.main"
    env_file:
      - .env
    depends_on:
      - backend
      - db_frontend
      - remind_telegram_worker
      - remind_telegram_beat
    restart: always
    volumes:
      - redis_data:/data

  db_frontend:
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER_FRONTEND}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_FRONTEND}
      POSTGRES_DB: ${POSTGRES_DB_FRONTEND}
    ports:
      - "5433:5432"
    volumes:
      - frontend_data:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis:alpine3.20
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  remind_telegram_worker:
    build:
      dockerfile: Dockerfile-Remind
    volumes:
      - redis_data:/data
    env_file:
      - .env
    command:
      - "./wait-for-it.sh"
      - "db_remind:5432"
      - "--"
      - "supervisord"
      - "-c"
      - "/etc/supervisor/conf.d/supervisord.conf"
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - db_remind
    restart: always

  remind_telegram_beat:
    build:
      dockerfile: Dockerfile-Remind
    volumes:
      - redis_data:/data
    env_file:
      - .env
    command:
      - "./wait-for-it.sh"
      - "db_remind:5432"
      - "--"
      - "celery"
      - "-A"
      - "remind.telegram_bot.celery_telegram"
      - "beat"
      - "--loglevel=info"
    depends_on:
      - redis
      - db_remind
    restart: always

  db_remind:
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER_REMIND}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_REMIND}
      POSTGRES_DB: ${POSTGRES_DB_REMIND}
    ports:
      - "5434:5432"
    volumes:
      - remind_data:/var/lib/postgresql/data/
    restart: always

volumes:
  backend_data:
  frontend_data:
  remind_data:
  redis_data:
