services:
  backend:
    build:
      context: backend/
    command:
      - "uvicorn"
      - "main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
  db:
    image: postgres:16.4
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - backend_data:/var/lib/postgresql/data/
    restart: always
  frontend:
    build:
      context: frontend/telegram_bot/
    command:
      - "python"
      - "main.py"
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - frontend_data:/var/lib/postgresql/data/
    restart: always
#  broker:
#    image: redis

volumes:
  - backend_data:
  - frontend_data:
