"""Update back sessions (session_id UUID -> str)

Revision ID: 146d9c4bad64
Revises: b1da0994d30b
Create Date: 2024-11-07 17:57:08.897756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '146d9c4bad64'
down_revision: Union[str, None] = 'b1da0994d30b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'session_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
    # ### end Alembic handlers_commands ###


def downgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'session_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic handlers_commands ###
