"""update refresh_token in users

Revision ID: 2dd94edf5bf9
Revises: 0f0e45ecd628
Create Date: 2024-11-25 15:48:11.438994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd94edf5bf9'
down_revision: Union[str, None] = '0f0e45ecd628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('users_refresh_token_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_refresh_token_key', 'users', ['refresh_token'])
    op.alter_column('users', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
