"""Add remind_time and count_repeat in habits

Revision ID: 55f079e1592e
Revises: 387a7ed09854
Create Date: 2024-10-29 17:39:19.720627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f079e1592e'
down_revision: Union[str, None] = '387a7ed09854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('remind_time', sa.Time(), nullable=False))
    op.add_column('habits', sa.Column('count_repeat', sa.Integer(), nullable=True))
    # ### end Alembic handlers_commands ###


def downgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'count_repeat')
    op.drop_column('habits', 'remind_time')
    # ### end Alembic handlers_commands ###
