"""Add last_time_check in habittracker

Revision ID: 5b8b549b603c
Revises: 7eca77739185
Create Date: 2024-10-30 14:00:43.584260

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b8b549b603c"
down_revision: Union[str, None] = "7eca77739185"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "habittracker", sa.Column("last_time_check", sa.DateTime(), nullable=False)
    )
    # ### end Alembic handlers_commands ###


def downgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    op.drop_column("habittracker", "last_time_check")
    # ### end Alembic handlers_commands ###
