"""Add count_repeat in habits

Revision ID: 711ac6f94b57
Revises: ef086068bfa6
Create Date: 2024-10-21 15:38:29.183618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '711ac6f94b57'
down_revision: Union[str, None] = 'ef086068bfa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('count_repeat', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'count_repeat')
    # ### end Alembic commands ###
