"""Add password in users

Revision ID: 77995c4741e5
Revises: 2d90fa40cbe2
Create Date: 2024-10-18 10:40:55.251654

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77995c4741e5"
down_revision: Union[str, None] = "2d90fa40cbe2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(length=50), nullable=False))
    op.add_column("users", sa.Column("password", sa.String(), nullable=True))
    op.create_unique_constraint(None, "users", ["username"])
    op.drop_column("users", "name")
    # ### end Alembic handlers_commands ###


def downgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "password")
    op.drop_column("users", "username")
    # ### end Alembic handlers_commands ###
