"""Replace count_repeat from habittracker to habits

Revision ID: 7e79a42d2918
Revises: a5e655358367
Create Date: 2024-10-30 13:19:12.683008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e79a42d2918'
down_revision: Union[str, None] = 'a5e655358367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'count_repeat')
    op.add_column('habittracker', sa.Column('count_repeat', sa.Integer(), nullable=True))
    # ### end Alembic handlers_commands ###


def downgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    op.drop_column('habittracker', 'count_repeat')
    op.add_column('habits', sa.Column('count_repeat', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic handlers_commands ###
