"""Move 'refresh_token' to sessions

Revision ID: 8c4814c01357
Revises: 44aed270adad
Create Date: 2024-10-21 11:01:39.723966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c4814c01357'
down_revision: Union[str, None] = '44aed270adad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('refresh_token', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'sessions', ['refresh_token'])
    op.drop_constraint('users_refresh_token_key', 'users', type_='unique')
    op.drop_column('users', 'refresh_token')
    # ### end Alembic handlers_commands ###


def downgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_refresh_token_key', 'users', ['refresh_token'])
    op.drop_constraint(None, 'sessions', type_='unique')
    op.drop_column('sessions', 'refresh_token')
    # ### end Alembic handlers_commands ###
