"""Add email in users

Revision ID: 97e847791fc3
Revises: 711ac6f94b57
Create Date: 2024-10-21 18:58:48.347263

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97e847791fc3"
down_revision: Union[str, None] = "711ac6f94b57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(), nullable=False))
    # ### end Alembic handlers_commands ###


def downgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email")
    # ### end Alembic handlers_commands ###
