"""Delete count_repeat from habits

Revision ID: 9acd2ccb14db
Revises: 6b11517ae9a6
Create Date: 2024-10-29 17:31:13.931643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9acd2ccb14db'
down_revision: Union[str, None] = '6b11517ae9a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'count_repeat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('count_repeat', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
