"""Add token in users

Revision ID: a474fbf65ad6
Revises: 77995c4741e5
Create Date: 2024-10-18 12:46:09.408353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a474fbf65ad6'
down_revision: Union[str, None] = '77995c4741e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('users', sa.Column('token', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['token'])
    op.drop_column('users', 'password')
    # ### end Alembic handlers_commands ###


def downgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'token')
    op.drop_column('users', 'password_hash')
    # ### end Alembic handlers_commands ###
