"""Correct UUID

Revision ID: b1da0994d30b
Revises: 8eb23d6c5667
Create Date: 2024-11-07 17:42:45.276622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1da0994d30b'
down_revision: Union[str, None] = '8eb23d6c5667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sessions', ['session_id'])
    # ### end Alembic handlers_commands ###


def downgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='unique')
    # ### end Alembic handlers_commands ###
