"""Correct last_time_check

Revision ID: b90590c4deb6
Revises: 5b8b549b603c
Create Date: 2024-10-30 14:04:08.252825

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b90590c4deb6"
down_revision: Union[str, None] = "5b8b549b603c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic handlers_commands ###


def downgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic handlers_commands ###
