"""Change salt and password_hash to binary

Revision ID: bfd2fe8e9b3d
Revises: d9745abb409e
Create Date: 2024-10-21 08:19:32.618531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd2fe8e9b3d'
down_revision: Union[str, None] = 'd9745abb409e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'salt',
            existing_type=sa.VARCHAR(),
            type_=sa.LargeBinary(),
            existing_nullable=False,
            postgresql_using='salt::bytea')
    op.alter_column('users', 'password_hash',
        existing_type=sa.VARCHAR(),
        type_=sa.LargeBinary(),
        existing_nullable=False,
        postgresql_using='password_hash::bytea')
    # ### end Alembic handlers_commands ###


def downgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
            existing_type=sa.LargeBinary(),
            type_=sa.VARCHAR(),
            existing_nullable=False,
            postgresql_using='salt::bytea')
    op.alter_column('users', 'salt',
            existing_type=sa.LargeBinary(),
            type_=sa.VARCHAR(),
            existing_nullable=False,
            postgresql_using='password_hash::bytea')
    # ### end Alembic handlers_commands ###
