"""Change salt and password_hash to binary

Revision ID: cbf87f0e8fb7
Revises: bfd2fe8e9b3d
Create Date: 2024-10-21 08:44:11.867429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbf87f0e8fb7'
down_revision: Union[str, None] = 'bfd2fe8e9b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
