"""remove salt from users

Revision ID: cd1f03ad80a4
Revises: 0df1d3670656
Create Date: 2024-11-21 21:17:39.194654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd1f03ad80a4'
down_revision: Union[str, None] = '0df1d3670656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'salt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt', postgresql.BYTEA(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
