"""Add salt in users

Revision ID: d9745abb409e
Revises: a474fbf65ad6
Create Date: 2024-10-21 07:53:44.212372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9745abb409e'
down_revision: Union[str, None] = 'a474fbf65ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt', sa.String(), nullable=False))
    op.add_column('users', sa.Column('refresh_token', sa.String(), nullable=False))
    op.drop_constraint('users_token_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['refresh_token'])
    op.drop_column('users', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_token_key', 'users', ['token'])
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'salt')
    # ### end Alembic commands ###
