"""Add done in habits

Revision ID: ef086068bfa6
Revises: 8c4814c01357
Create Date: 2024-10-21 15:32:50.850453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef086068bfa6'
down_revision: Union[str, None] = '8c4814c01357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('done', sa.Boolean(), nullable=True))
    # ### end Alembic handlers_commands ###


def downgrade() -> None:
    # ### handlers_commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'done')
    # ### end Alembic handlers_commands ###
